# Generated by Django 5.2.3 on 2025-07-01 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('cant_dias', models.IntegerField()),
                ('precio', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='socio',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='plan',
        ),
        migrations.AddField(
            model_name='socio',
            name='plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socios.plan'),
            preserve_default=False,
        ),
    ]
