# Generated by Django 5.2.3 on 2025-07-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_plan_remove_socio_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago']},
        ),
        migrations.RenameField(
            model_name='socio',
            old_name='fecha_inicio',
            new_name='fecha_inscripcion',
        ),
        migrations.RenameField(
            model_name='socio',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='cant_dias',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='huella_id',
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='cant_dias_semana',
            field=models.IntegerField(default=3, help_text='Días permitidos por semana (2, 3 o 5)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado administrativo del socio'),
        ),
        migrations.AddField(
            model_name='socio',
            name='codigo_acceso',
            field=models.CharField(default='temp', help_text='Código de acceso del socio', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='mes_correspondiente',
            field=models.DateField(help_text='Mes al que corresponde el pago (primer día del mes)'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='pago',
            unique_together={('socio', 'mes_correspondiente')},
        ),
    ]
