# Generated by Django 5.2.3 on 2025-07-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_pago_unique_together_pago_fecha_inicio_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='huella_registrada',
            field=models.BooleanField(default=False, help_text='Si tiene huella registrada'),
        ),
        migrations.AddField(
            model_name='socio',
            name='huella_template',
            field=models.TextField(blank=True, help_text='Template de huella dactilar codificado', null=True),
        ),
    ]
